/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author DiegoDM
 */
public class Enfrentamiento extends javax.swing.JFrame {

    /**
     * Creates new form Enfrentamiento
     */
    //Hay que revisar los argumentos del presunto constructor de Enfrentamiento 
    /*public Enfrentamiento(Pelea enfrentamiento) {
        initComponents();
        // Código para mostrar la información del peleador en los labes 
        // Muestra el nombre, la habilidad, etc. 
        // Cuando pique el boton hay que desaparecerlo para que ya no apueste o hacer ineditable el btón 
        // O cuando ya haya apostado mandar un mensaje 
    }*/
    public Enfrentamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreGanador = new javax.swing.JLabel();
        jLabelFondoGanador = new javax.swing.JLabel();
        jButtonPeleador1 = new javax.swing.JButton();
        jButtonPeleador2 = new javax.swing.JButton();
        jLabelPeleador1 = new javax.swing.JLabel();
        jLabelPeleador2 = new javax.swing.JLabel();
        jTextFieldApuestaP1 = new javax.swing.JTextField();
        jTextFieldApuestaP2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreGanador.setFont(new java.awt.Font("TeXGyreCursor", 3, 23)); // NOI18N
        jLabelNombreGanador.setForeground(new java.awt.Color(155, 107, 10));
        jLabelNombreGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelNombreGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 160, 40));

        jLabelFondoGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoGanador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/win.png"))); // NOI18N
        getContentPane().add(jLabelFondoGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 130));

        jButtonPeleador1.setText("Apostar");
        jButtonPeleador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeleador1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPeleador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        jButtonPeleador2.setText("Apostar");
        jButtonPeleador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeleador2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPeleador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));

        jLabelPeleador1.setText("Info del peleador");
        getContentPane().add(jLabelPeleador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 70));

        jLabelPeleador2.setText("Info del peleador");
        getContentPane().add(jLabelPeleador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 110, 70));

        jTextFieldApuestaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApuestaP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldApuestaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));
        getContentPane().add(jTextFieldApuestaP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 90, -1));

        jLabel1.setFont(new java.awt.Font("STIXGeneral", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("$");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 20, 30));

        jLabel2.setFont(new java.awt.Font("STIXGeneral", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 20, 30));

        jButtonCerrar.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jButtonCerrar.setText("X");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 0, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPeleador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeleador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPeleador1ActionPerformed

    private void jButtonPeleador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeleador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPeleador2ActionPerformed

    private void jTextFieldApuestaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApuestaP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApuestaP1ActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonPeleador1;
    private javax.swing.JButton jButtonPeleador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondoGanador;
    private javax.swing.JLabel jLabelNombreGanador;
    private javax.swing.JLabel jLabelPeleador1;
    private javax.swing.JLabel jLabelPeleador2;
    private javax.swing.JTextField jTextFieldApuestaP1;
    private javax.swing.JTextField jTextFieldApuestaP2;
    // End of variables declaration//GEN-END:variables
}
